db:
  server: www.test.com
  port: 13306
  username: root
  password: 'FJEOIRFWQ132EW'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    host: www.test.com
    password: ${common.password}
    database: 1
common:
  password: "FJEOIRFWQ132EW"